"""Create slides table

Revision ID: 8216e25a2be3
Revises: 
Create Date: 2024-12-08 22:16:46.337026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8216e25a2be3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slideName', sa.String(length=255), nullable=False),
    sa.Column('slidePath', sa.String(length=255), nullable=False),
    sa.Column('slideUrl', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slides')
    # ### end Alembic commands ###
